### post att
Post http://localhost:3000/attendance/create
Content-Type: application/json

{
    "date" : "2026-03-22",
    "status" : "present",
    "enrollmentId" : "9"
}

### ll
DELETE http://localhost:3000/attendance/remove
