### post enrollment
POST http://localhost:3000/enrollment/enroll/create
Content-Type: application/json

{
    "studentId" : "2",
    "adminId" : "1",
    "courseId" : "3"
}

### Get ALL Stu
GET http://localhost:3000/enrollment/enroll/allstu

