### Create Combined Student
Post http://localhost:3000/student/combined/create
Content-Type: application/json

{
    "name" : "k31",
    "age" : "17",
    "phone" : "010-2222-2222",
    "pPhone" : "010-3333-3333",
    "email" : "dnjsxoghd@naver.com",
    "memo" : "Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World Hello-World ",
    "courses" : ["1", "2"]
}

### Update Student
POST http://localhost:3000/student/update/1
Content-Type: application/json

{
    "age" : "302",
    "phone" : "010-4444-3121",
    "pPhone" : "010-3333-3241"
}

### Search Test
Get http://localhost:3000/student/search?keword=홍


