### Create Admin
POST http://localhost:3000/admin/secure
Content-Type: application/json

{
    "email" : "wlwlwl3121@naver.com",
    "password" : "q2tlxm@123"
}

### Post Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "admin@test.com",
    "password" : "1234"
}

### Login
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJpYXQiOjE3NzEzMjczNzcsImV4cCI6MTc3MTMzMDk3N30.-duEo7-zwJc8xsj_AM2Z-EBciP6_BSP8xLx_070ShwA