### Create Admin
POST http://localhost:3000/admin/secure
Content-Type: application/json

{
    "email" : "koala3121@naver.com",
    "password" : "q2tlxm@123"
}

### Post Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "admin@test.com",
    "password" : "1234"
}

### Login
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJpYXQiOjE3NzE0MTI0MjcsImV4cCI6MTc3MTQxNjAyN30.VbUHdunoIvsIxjYdlvUm5b-37vGbgEWUyPd2mhzfVZM